" Base Config " {{{
" 让配置变更立即生效
autocmd BufWritePost $MYVIMRC source $MYVIMRC
" 开启实时搜索功能
set incsearch
" 搜索时大小写不敏感
set ignorecase
" 关闭兼容模式
set nocompatible
" vim 自身命令行模式智能补全
set wildmenu
" }}}

" Command Config " {{{
" 定义快捷键的前缀，即<Leader>
let mapleader=";"
map h <UP>
map j <LEFT>
map k <DOWN>
map l <RIGHT>
" 设置快捷键将选中文本块复制至系统剪贴板
vnoremap <Leader>y "+y
" 设置快捷键将系统剪贴板内容粘贴至 vim
nmap <Leader>p "+p
" 定义快捷键关闭当前分割窗口
nmap <Leader>q :q<CR>
" 定义快捷键保存当前窗口内容
nmap <Leader>w :w<CR>
" 定义快捷键保存所有窗口内容并退出 vim
nmap <Leader>WQ :wa<CR>:q<CR>
" 不做任何保存，直接退出 vim
nmap <Leader>Q :qa!<CR>
" 依次遍历子窗口
nnoremap nw <C-W><C-W>
" 跳转至右方的窗口
nnoremap <Leader>lw <C-W>l
" 跳转至左方的窗口
nnoremap <Leader>jw <C-W>h
" 跳转至上方的子窗口
nnoremap <Leader>hw <C-W>k
" 跳转至下方的子窗口
nnoremap <Leader>kw <C-W>j
" 定义快捷键在结对符之间跳转
nmap <Leader>M %
" 设置折叠方法为marker
nmap <Leader><Leader>fm :set foldmethod=marker<CR>
" }}}

" Format Config " {{{

" }}}

" Apperance " {{{
" colorScheme
set background=dark
colorscheme solarized8_dark_flat
"sotp cursor blinking
set gcr=a:block-blinkon0
" delete tool bar
set guioptions-=T
" 总是显示状态栏
set laststatus=2
" 显示光标当前位置
set ruler
" 开启行号显示
set number
" 高亮显示当前行/列
set cursorline
set cursorcolumn
" 高亮显示搜索结果
set hlsearch
" 设置 gvim 显示字体
set guifont=Consolas:h11
" 禁止折行
set nowrap
" 设置状态栏主题风格
let g:Powerline_colorscheme='solarized256'
" }}}
